### ISSUE TITLE
未考虑单双周

### ISSUE THREAD

**Issue by LadderOperator** [HaoNShi/AiSchedule_Adapter#1]
大佬你是小爱课程表的第一个南京大学研究生课表那个吗？
我终于找到你了，你提交的版本似乎对单双周课程解析有问题，希望可以改一下
不过之前因为找不到你，所以我只好自己也写了一个版本

**Comment by codelumos** [comment]
你好，非常感谢你的反馈。
在进行第一版开发时我的课表中不存在特殊情况，所以旧版确实会在某些特殊情况下导入时存在问题。
在上周我已经更新迭代过一次版本，并将旧版本下线。新版本适配了更多的情形，你可以尝试重新选择更新后的版本，看一下是否还存在导入问题。
如果还存在问题，麻烦将您的课表内容发给我进一步适配，我的邮箱是haonshi@qq.com。
